language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - RUN=vendor/bin/phing

script: ${RUN}

before_script:
  - composer selfupdate
  - composer --version
  - composer install --prefer-dist --verbose
